name: CI/CD

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
      MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"

      - name: Install Dependencies
        run: |
          echo "$MODAL_TOKEN_ID and $MODAL_TOKEN_SECRET"
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install modal

      - name: Configure Modal Authentication
        run: |
          echo "Configuring Modal authentication"
          echo "$MODAL_TOKEN_ID and $MODAL_TOKEN_SECRET"
          mkdir -p ~/.modal
          cat > ~/.modal/config.toml <<EOF
          [api_token]
          token_id = "${MODAL_TOKEN_ID}"
          token_secret = "${MODAL_TOKEN_SECRET}"
          EOF
          echo "Modal authentication configured"

      - name: Deploy to Modal
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            modal deploy --env ask-ami main_modal.py
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            modal deploy --env ask-ami-dev main_modal.py
          fi
