name: CI/CD

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
      MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install modal

      - name: Check if Modal secrets are present
        run: |
          if [ -z "$MODAL_TOKEN_ID" ]; then
            echo "❌ MODAL_TOKEN_ID is NOT set"
            exit 1
          else
            echo "✅ MODAL_TOKEN_ID is set"
          fi

          if [ -z "$MODAL_TOKEN_SECRET" ]; then
            echo "❌ MODAL_TOKEN_SECRET is NOT set"
            exit 1
          else
            echo "✅ MODAL_TOKEN_SECRET is set"
          fi

      - name: Authenticate Modal
        run: |
          echo "🔐 Setting Modal token"
          modal token set --token-id "$MODAL_TOKEN_ID" --token-secret "$MODAL_TOKEN_SECRET"
          echo "✅ Modal authentication complete"

      - name: Deploy to Modal
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            modal deploy --env ask-ami main_modal.py
          elif [[ "${GITHUB_REF}" == "refs/heads/dev" ]]; then
            modal deploy --env ask-ami-dev main_modal.py
          fi
